name: sombat
favicon: null
layout_spectrum: 0.19437596574425697
typography_spectrum: 0.6258802521042526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4850843474268913
  lightness: 0.10877390252426267
  saturation: 0.16006591985933483
  rhythmicContrast: 0.9964209385216236
purpose: []
